# Generated by Django 5.0.6 on 2024-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.UUIDField()),
                ('produto_id', models.PositiveIntegerField()),
                ('qtd_produto', models.PositiveIntegerField()),
                ('preco_unitario', models.FloatField()),
            ],
        ),
    ]
