# Generated by Django 5.0.6 on 2024-05-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.BigIntegerField(default=0),
        ),
    ]
